### ISSUE TITLE
Udemy student - there is an error in udemy course instructions, frontend will not build

### ISSUE THREAD

**Issue by afewell** [zreecespieces/jamstack-ecommerce-course#3]
Hi, I am on module 36 in the course, creating a gatsby project. I followed the instructions and updated notes explicitly, I installed the exact gatsby version you specified, replaced the package.json file with the one you specified, deleted the node_modules folder, ran npm install, and still when I run npm run develop, it has errors and will not build. 

Here is the output:

```
afewell@afewell-a01 frontend % npm run develop

> gatsby-starter-default@0.1.0 develop /Users/afewell/git/forks/afewell/var_x/frontend
> gatsby develop

internal/modules/cjs/loader.js:1102
      throw new ERR_REQUIRE_ESM(filename, parentPath, packageJsonPath);
      ^

Error [ERR_REQUIRE_ESM]: Must use import to load ES Module:
/Users/afewell/git/forks/afewell/var_x/frontend/node_modules/remark-mdx/index.js
require() of ES modules is not supported.
require() of /Users/afewell/git/forks/afewell/var_x/frontend/node_modules/remark-mdx/index.js from
/Users/afewell/git/forks/afewell/var_x/frontend/node_modules/gatsby-recipes/dist/graphql-server/server.js is an
 ES module file as it is a .js file whose nearest parent package.json contains "type": "module" which defines
all .js files in that package scope as ES modules.
Instead rename index.js to end in .cjs, change the requiring code to use import(), or remove "type": "module"
from /Users/afewell/git/forks/afewell/var_x/frontend/node_modules/remark-mdx/package.json.

    at new NodeError (internal/errors.js:322:7)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1102:13)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:12)
    at Module.require (internal/modules/cjs/loader.js:974:19)
    at require (internal/modules/cjs/helpers.js:93:18)
    at Object.<anonymous> (/Users/afewell/git/forks/afewell/var_x/frontend/node_modules/gatsby-recipes/dist/gra
phql-server/server.js:52:17)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Module.load (internal/modules/cjs/loader.js:950:32) {
  code: 'ERR_REQUIRE_ESM'
}


info We're shipping new features! For final testing, we're rolling them out first to a small % of Gatsby users
and your site was automatically chosen as one of them. With your help, we'll then release them to everyone in
the next minor release.

We greatly appreciate your help testing the change. Please report any feedback good or bad in the umbrella
issue. If you do encounter problems, please disable the flag by setting it to false in your gatsby-config.js
like:

flags: {
  THE_FLAG: false
}

The following flags were automatically enabled on your site:
- DEV_SSR · (Umbrella Issue (https://gatsby.dev/dev-ssr-feedback)) · Server Side Render (SSR) pages on full
reloads during develop. Helps you detect SSR bugs and fix them without needing to do full builds.


 ERROR 

There was a problem loading plugin "gatsby-plugin-image". Perhaps you need to install its package?
Use --verbose to see actual error.


 ERROR #10226  CONFIG

Couldn't find the "gatsby-plugin-image" plugin declared in
"/Users/afewell/git/forks/afewell/var_x/frontend/gatsby-config.js".

Tried looking for a local plugin in
/Users/afewell/git/forks/afewell/var_x/frontend/plugins/gatsby-plugin-image.

Tried looking for an installed package in the following paths:
 - /Users/afewell/git/forks/afewell/var_x/frontend/node_modules/gatsby/dist/bootstrap/load-themes/node_modules/
gatsby-plugin-image
 - /Users/afewell/git/forks/afewell/var_x/frontend/node_modules/gatsby/dist/bootstrap/node_modules/gatsby-plugi
n-image
 - /Users/afewell/git/forks/afewell/var_x/frontend/node_modules/gatsby/dist/node_modules/gatsby-plugin-image
 - /Users/afewell/git/forks/afewell/var_x/frontend/node_modules/gatsby/node_modules/gatsby-plugin-image
 - /Users/afewell/git/forks/afewell/var_x/frontend/node_modules/gatsby-plugin-image
 - /Users/afewell/git/forks/afewell/var_x/node_modules/gatsby-plugin-image
 - /Users/afewell/git/forks/afewell/node_modules/gatsby-plugin-image
 - /Users/afewell/git/forks/node_modules/gatsby-plugin-image
 - /Users/afewell/git/node_modules/gatsby-plugin-image
 - /Users/afewell/node_modules/gatsby-plugin-image
 - /Users/node_modules/gatsby-plugin-image
 - /node_modules/gatsby-plugin-image

not finished open and validate gatsby-configs - 0.139s

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! gatsby-starter-default@0.1.0 develop: `gatsby develop`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the gatsby-starter-default@0.1.0 develop script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/afewell/.npm/_logs/2022-01-09T17_40_38_848Z-debug.log
afewell@afewell-a01 frontend % npm run develop
```

**Comment by afewell** [comment]
I am just using latest versions now, and it builds fine. I may run into some slight differences as I progress, but I feel its worth it to ensure I am familiar with the latest. Thanks!
